default_install_hook_types: ["pre-commit", "commit-msg"]
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.6.0" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        files: \.(md)$
        stages:
          - commit
        args:
          - "--prose-wrap"
          - "always"
  - repo: "https://github.com/igorshubovych/markdownlint-cli"
    rev: v0.31.1
    hooks:
      - id: markdownlint
        verbose: true
  - repo: https://github.com/psf/black
    rev: "22.3.0" # Use the sha or tag you want to point at
    hooks:
      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: black
        language: python
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [python, pyi]
        verbose: true
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        verbose: true
  - repo: https://github.com/commitizen-tools/commitizen
    rev: master
    hooks:
      - id: commitizen
        verbose: true
        stage:
          - commit