name: SQL Deployment Tools - Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Build Executable (Windows)
        run: |
          ./platform/windows/build.bat

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/windows/sql-deployment-tools.exe
        name: Upload Executable