name: SQL Deployment Tools - Mac OSX

on:
  workflow_run:
    workflows: ["SQL Deployment Tools CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          fetch-depth: 0

      - name: Build Executable (Mac OSX)
        run: |
          sh ./platform/mac_osx/build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/macosx/sql-deployment-tools
        name: Upload Executable

      - name: 'Get Latest tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ steps.previoustag.outputs.tag }}
          files: dist/macosx/sql-deployment-tools
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITIZEN }}
