name: SQL Deployment Tools - Windows

concurrency:
  group: release
  cancel-in-progress: true

on:
  workflow_run:
    workflows: ["SQL Deployment Tools CI", "SQL Deployment Tools - Debian"]
    branches: [main]
    types:
      - completed

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: ./requirements/*.txt
      - run: pip install -r ./requirements/build.txt
      - run: pip install -r ./requirements/test.txt

  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository
        with:
          fetch-depth: 0

      - name: Build Executable (Windows)
        run: |
          ./platform/windows/build.bat

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/windows/sql-deployment-tools.exe
        name: Upload Executable

      - name: 'Get Latest tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ steps.previoustag.outputs.tag }}_windows
          files: dist/windows/sql-deployment-tools.exe
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITIZEN }}
