name: SQL Deployment Tools - Debian

on:
  workflow_run:
    workflows: ["SQL Deployment Tools CI"]
    branches: [main]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout Repository

      - name: Build Executable (Debian)
        run: |
          sh ./platform/linux_debian/build.sh

      - uses: actions/upload-artifact@v3
        with:
          name: exe
          path: dist/debian/sql-deployment-tools
        name: Upload Executable

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "CHANGELOG.md"
          tag_name: ${{ env.REVISION }}
          files: dist/debian/sql-deployment-tools
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITIZEN }}
